### ISSUE TITLE
complete editor page

### ISSUE THREAD

**Issue by criticalbh** [criticalbh/vanilla-web-components#5]
This application is built with vanilla JS web components for gothinkster real world examples. One missing feature is left to complete the gothinkster specification of realworld example and that is editor page to write/edit article.

**Comment by shilpiverma509** [comment]
Hey @criticalbh , can you give some more details

**Comment by criticalbh** [comment]
Hello @shilpiverma509, of course I can. Idea that stands behind this repository is https://github.com/gothinkster/realworld.

To see editor page in action you can visit any completed implementation such as react-redux example [here](https://react-redux.realworld.io/#/?_k=4plns9). 

To start with this repository you will need `yarn`.

Once you clone the repository in root project directory run `yarn` to install node dependencies, once that is completed execute `yarn start` which will bring up development server on `localhost:8080`.
